sensor:
  - name: ${s_2036}
    address: 2036
    unit_of_measurement: ${meas_steps}
    value_type: U_WORD
    min_value: 0
    max_value: ${flap_max}
    step: 1
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    
  - name: ${s_2202}
    address: 2202
    min_value: 0
    max_value: 25
    step: 1
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2212}
    address: 2212
    min_value: 0
    max_value: ${max_cap}
    step: 1
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    
  - name: ${s_3201}
    address: 3201
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

switch:
  - name: ${s_2037}
    address: 2037
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2203}
    address: 2203
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2213}
    address: 2213
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
