number:
  - name: ${s_2208}
    address: 2208
    min_value: 0
    max_value: 25
    step: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true
   
  - name: ${s_2218}
    address: 2218
    min_value: 0
    max_value: ${max_cap}
    step: 1
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true

sensor:
  - name: ${s_3204}
    address: 3204
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    
switch:
  - name: ${s_2209}
    address: 2209
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}    
    use_write_multiple: true
    
  - name: ${s_2219}
    address: 2219
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    use_write_multiple: true
    
