number:
  - name: ${s_2040}
    address: 2040
    unit_of_measurement: ${meas_steps}
    value_type: U_WORD
    min_value: 0
    max_value: ${flap_max}
    step: 1
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2206}
    address: 2206
    min_value: 0
    max_value: 25
    step: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2216}
    address: 2216
    min_value: 0
    max_value: ${max_cap}
    step: 1
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

sensor:
  - name: ${s_3203}
    address: 3203
    unit_of_measurement: m3/h
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

switch: 
  - name: ${s_2041}
    address: 2041
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2207}
    address: 2207
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}

  - name: ${s_2217}
    address: 2217
    bitmask: 0
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
