# Note: this is the white module
esp32:
  board: esp32-s3-devkitc-1 
  framework:
    type: arduino
    version: latest
###
# Uart Settings
###
uart:
  id: uart_modbus
  tx_pin: 2
  rx_pin: 1
  baud_rate: 19200
  data_bits: 8
  stop_bits: 1
  parity: EVEN
  debug:
    direction: BOTH